services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000  # Running Django with the default WSGI server
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=mysite.settings
      - CELERY_BROKER_URL=rediss://red-ctstd68gph6c738ee8d0:qVcasI3cTrXWEUAgl98FfVRQRdAJXPV6@oregon-redis.render.com:6379
      - CELERY_RESULT_BACKEND=rediss://red-ctstd68gph6c738ee8d0:qVcasI3cTrXWEUAgl98FfVRQRdAJXPV6@oregon-redis.render.com:6379
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A mysite worker --loglevel=info  # Running Celery worker
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=mysite.settings
      - CELERY_BROKER_URL=rediss://red-ctstd68gph6c738ee8d0:qVcasI3cTrXWEUAgl98FfVRQRdAJXPV6@oregon-redis.render.com:6379
      - CELERY_RESULT_BACKEND=rediss://red-ctstd68gph6c738ee8d0:qVcasI3cTrXWEUAgl98FfVRQRdAJXPV6@oregon-redis.render.com:6379
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
