services:
  - type: web
    name: django-adminlte
    plan: starter # This is the free plan.
    env: python # Specify the environment for Django (Python).
    region: oregon # Updated to Oregon region.
    buildCommand: "./build.sh" # Command to build your project (ensure this script exists).
    startCommand: "gunicorn core.wsgi:application" # Command to start your Django app.
    envVars:
      - key: DEBUG
        value: "False" # Set DEBUG to False for production.
      - key: SECRET_KEY
        generateValue: true # Render will generate a secure SECRET_KEY.
      - key: WEB_CONCURRENCY
        value: "4" # Number of worker processes for Gunicorn.
      - key: DATABASE_URL
        fromDatabase: postgres # Automatically set DATABASE_URL from the PostgreSQL service.
      - key: REDIS_URL
        fromService: redis # If you're using Redis, you can define the URL here.
      - key: ALLOWED_HOSTS
        value: "https://imagestock-backend.onrender.com" # Replace with your actual Render app URL.

  - type: database
    name: postgres-db
    plan: starter # Free database plan.
    region: oregon # Updated to Oregon region.
    env: postgres # Specifies the environment for PostgreSQL.

  - type: redis
    name: redis
    plan: free # Free Redis plan (if you're using Redis).
    region: oregon # Updated to Oregon region.
